extends Node

const DICT_THEMES = {
	'DEFAULT': {
		'PRIMARY': "CFEBCE",
		'SECONDARY': "FFFFFF",
		'TERTIARY': "FF9500",
		'DARK': "2C2C2C",
		'DANGER': "FF004D",
		'TRANSLUCENT': "00FFFFFF",
		'SHADOW': "802C2C2C"
	}
}
